Repository taiga-family/maskito, pull requests merged in 2024-01, with the labels that each got.

#864 feat(kit): `Number` allows to enter full width numbers
  projects/demo-integrations/src/tests/kit/number/number-fullwidth-to-halfwidth.cy.ts
  projects/kit/src/lib/constants/unicode-characters.ts
  projects/kit/src/lib/masks/number/number-mask.ts
  projects/kit/src/lib/masks/number/processors/fullwidth-to-halfwidth-preprocessor.ts
  projects/kit/src/lib/masks/number/processors/index.ts
  projects/kit/src/lib/masks/number/utils/tests/to-half-width-number.spec.ts
  projects/kit/src/lib/masks/number/utils/to-half-width-number.ts
Labels: community contribution

#874 fix(kit): `maskitoParseNumber` cannot parse prefix/postfix with points
  projects/kit/src/lib/masks/number/utils/parse-number.ts
  projects/kit/src/lib/masks/number/utils/tests/parse-number.spec.ts
Labels: ready to merge

#875 chore(demo-integrations): tests for cases when `Number` has postfix with point
  projects/demo-integrations/cypress.config.ts
  projects/demo-integrations/src/tests/component-testing/number-postfix/number-postfix-with-point.cy.ts
  projects/demo-integrations/src/tests/component-testing/test.cy.ts
  projects/demo-integrations/src/tests/component-testing/utils.ts
  projects/kit/src/lib/masks/number/tests/number-mask.spec.ts
Labels: ready to merge

#876 feat!: bump Firefox browser support (55+ => 87+)
  .browserslistrc
  projects/demo/src/pages/documentation/browser-support/browser-support.component.ts
  projects/demo/tsconfig.app.json
  tsconfig.json
Labels: ready to merge

#881 feat(core): new built-in `maskitoStrictCompositionPlugin`
  projects/core/src/index.ts
  projects/core/src/lib/utils/index.ts
  projects/core/src/lib/utils/strict-composition-plugin.ts
  projects/demo/src/pages/documentation/plugins/examples/3-strict-composition/component.ts
  projects/demo/src/pages/documentation/plugins/examples/3-strict-composition/mask.ts
  projects/demo/src/pages/documentation/plugins/plugins.component.ts
  projects/demo/src/pages/documentation/plugins/plugins.module.ts
  projects/demo/src/pages/documentation/plugins/plugins.template.html
Labels: ready to merge

#882 fix(core): drop some excess dispatches of `Input`-event
  projects/core/src/lib/mask.ts
  projects/demo-integrations/src/tests/component-testing/placeholder/placeholder-dispatch-input-events.cy.ts
  projects/demo-integrations/src/tests/component-testing/utils.ts
  projects/kit/src/lib/processors/tests/with-placeholder.spec.ts
  projects/kit/src/lib/processors/with-placeholder.ts
Labels: ready to merge

#885 chore(demo): delete `@ts-nocheck` (no more required after Vue@3.4.0 update)
  projects/demo/src/pages/cypress/examples/5-react-async-predicate/react-app.tsx
  projects/demo/src/pages/frameworks/react/examples/2-element-predicate/awesome-input.tsx
  projects/demo/src/pages/frameworks/react/examples/2-element-predicate/index.tsx
  projects/demo/src/pages/frameworks/react/react-doc.component.ts
Labels: ready to merge

#894 ci: `on: workflow_dispatch` & `on: branches: ['release/*']` in `deploy.yml`
  .github/workflows/deploy.yml
Labels: ready to merge

#895 ci: `on: workflow_dispatch` in `deploy.yml`
  .github/workflows/deploy.yml
  .gitignore
Labels: ready to merge, v1

#908 chore(demo-integrations): stabilize command `mount` for Cypress CT
  projects/demo-integrations/src/support/component.ts
Labels: ready to merge

#909 chore(demo): use new modern Angular routing approach for documentation section `Kit`
  projects/demo/src/app/app.routes.ts
  projects/demo/src/pages/kit/date-range/date-range-mask-doc.component.ts
  projects/demo/src/pages/kit/date-range/date-range-mask-doc.module.ts
  projects/demo/src/pages/kit/date-range/examples/1-date-localization/component.ts
  projects/demo/src/pages/kit/date-range/examples/2-min-max/component.ts
  projects/demo/src/pages/kit/date-range/examples/3-min-max-length/component.ts
  projects/demo/src/pages/kit/date-range/examples/4-range-separator/component.ts
  projects/demo/src/pages/kit/date-range/index.ts
  projects/demo/src/pages/kit/date-time/date-time-mask-doc.component.ts
  projects/demo/src/pages/kit/date-time/date-time-mask-doc.module.ts
  projects/demo/src/pages/kit/date-time/examples/1-date-time-localization/component.ts
  projects/demo/src/pages/kit/date-time/examples/2-min-max/component.ts
  projects/demo/src/pages/kit/date-time/index.ts
  projects/demo/src/pages/kit/date/date-mask-doc.component.ts
  projects/demo/src/pages/kit/date/date-mask-doc.module.ts
  projects/demo/src/pages/kit/date/examples/1-localization/component.ts
  projects/demo/src/pages/kit/date/examples/2-min-max/component.ts
  projects/demo/src/pages/kit/date/index.ts
  projects/demo/src/pages/kit/number/examples/1-high-precision/component.ts
  projects/demo/src/pages/kit/number/examples/2-separators/component.ts
  projects/demo/src/pages/kit/number/examples/3-postfix/component.ts
  projects/demo/src/pages/kit/number/examples/4-decimal-zero-padding/component.ts
  projects/demo/src/pages/kit/number/examples/5-dynamic-decimal-zero-padding/component.ts
  projects/demo/src/pages/kit/number/index.ts
  projects/demo/src/pages/kit/number/number-mask-doc.component.ts
  projects/demo/src/pages/kit/number/number-mask-doc.module.ts
  projects/demo/src/pages/kit/template/kit-template-doc.component.ts
  projects/demo/src/pages/kit/template/kit-template-doc.module.ts
  projects/demo/src/pages/kit/template/kit-template-doc.template.html
  projects/demo/src/pages/kit/time/examples/1-modes/component.ts
  projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/component.ts
  projects/demo/src/pages/kit/time/index.ts
  projects/demo/src/pages/kit/time/time-mask-doc.component.ts
  projects/demo/src/pages/kit/time/time-mask-doc.module.ts
Labels: ready to merge

#910 chore(demo): use new modern Angular routing approach for documentation section `Recipes`
  projects/demo/src/app/app.routes.ts
  projects/demo/src/pages/recipes/card/card-doc.component.ts
  projects/demo/src/pages/recipes/card/card-doc.module.ts
  projects/demo/src/pages/recipes/card/examples/1-basic/component.ts
  projects/demo/src/pages/recipes/phone/examples/1-us-phone/component.ts
  projects/demo/src/pages/recipes/phone/examples/2-kz-phone/component.ts
  projects/demo/src/pages/recipes/phone/phone-doc.component.ts
  projects/demo/src/pages/recipes/phone/phone-doc.module.ts
  projects/demo/src/pages/recipes/placeholder/examples/1-cvc-code/component.ts
  projects/demo/src/pages/recipes/placeholder/examples/2-phone/component.ts
  projects/demo/src/pages/recipes/placeholder/examples/3-date/component.ts
  projects/demo/src/pages/recipes/placeholder/placeholder-doc.component.ts
  projects/demo/src/pages/recipes/placeholder/placeholder-doc.module.ts
  projects/demo/src/pages/recipes/postfix/examples/1-pattern-mask/component.ts
  projects/demo/src/pages/recipes/postfix/examples/2-postprocessor/component.ts
  projects/demo/src/pages/recipes/postfix/postfix-doc.component.ts
  projects/demo/src/pages/recipes/postfix/postfix-doc.module.ts
  projects/demo/src/pages/recipes/prefix/examples/1-pattern-mask/component.ts
  projects/demo/src/pages/recipes/prefix/examples/2-postprocessor/component.ts
  projects/demo/src/pages/recipes/prefix/prefix-doc.component.ts
  projects/demo/src/pages/recipes/prefix/prefix-doc.module.ts
  projects/demo/src/pages/recipes/textarea/examples/1-latin/component.ts
  projects/demo/src/pages/recipes/textarea/textarea-doc.component.ts
  projects/demo/src/pages/recipes/textarea/textarea-doc.module.ts
Labels: ready to merge

#816 fix(kit): `Number` has problems when prefix/postfix includes `decimalSeparator` symbol
  projects/demo-integrations/src/tests/component-testing/number-postfix/number-postfix-with-point.cy.ts
  projects/kit/src/lib/masks/number/number-mask.ts
  projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts
  projects/kit/src/lib/masks/number/plugins/not-empty-integer.plugin.ts
  projects/kit/src/lib/masks/number/processors/affixes-filter-preprocessor.ts
  projects/kit/src/lib/masks/number/processors/decimal-zero-padding-postprocessor.ts
  projects/kit/src/lib/masks/number/processors/initialization-only-preprocessor.ts
  projects/kit/src/lib/masks/number/processors/leading-zeroes-validation-postprocessor.ts
  projects/kit/src/lib/masks/number/processors/pseudo-character-preprocessor.ts
  projects/kit/src/lib/masks/number/processors/repeated-decimal-separator-preprocessor.ts
  projects/kit/src/lib/masks/number/processors/tests/leading-zeroes-validation-postprocessor.spec.ts
  projects/kit/src/lib/masks/number/processors/thousand-separator-postprocessor.ts
  projects/kit/src/lib/masks/number/processors/zero-precision-preprocessor.ts
  projects/kit/src/lib/masks/number/tests/number-mask.spec.ts
  projects/kit/src/lib/utils/extract-affixes.ts
  projects/kit/src/lib/utils/index.ts
Labels: community contribution

#921 fix(kit): `Number` should use zero-width space if prefix ends with decimal separator
  projects/demo-integrations/src/tests/kit/number/number-prefix-postfix.cy.ts
  projects/kit/src/lib/constants/unicode-characters.ts
  projects/kit/src/lib/masks/number/number-mask.ts
  projects/kit/src/lib/masks/number/processors/index.ts
  projects/kit/src/lib/masks/number/processors/not-empty-integer-part-preprocessor.ts
  projects/kit/src/lib/masks/number/processors/tests/not-empty-integer-part-preprocessor.spec.ts
  projects/kit/src/lib/masks/number/tests/number-mask.spec.ts
Labels: ready to merge

#927 chore(demo): improve some documentation examples (make them more framework agnostic)
  projects/demo/src/pages/kit/number/examples/3-postfix/component.ts
  projects/demo/src/pages/kit/number/examples/3-postfix/mask.ts
  projects/demo/src/pages/kit/number/number-mask-doc.component.ts
  projects/demo/src/pages/kit/number/number-mask-doc.template.html
  projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/component.ts
  projects/demo/src/pages/kit/time/examples/2-twelve-hour-format/mask.ts
  projects/demo/src/pages/recipes/phone/examples/2-kz-phone/component.ts
  projects/demo/src/pages/recipes/phone/examples/2-kz-phone/mask.ts
  projects/demo/src/pages/recipes/phone/examples/2-kz-phone/template.html
  projects/demo/src/pages/recipes/postfix/examples/2-postprocessor/component.ts
  projects/demo/src/pages/recipes/postfix/examples/2-postprocessor/mask.ts
  projects/demo/src/pages/recipes/prefix/examples/2-postprocessor/component.ts
  projects/demo/src/pages/recipes/prefix/examples/2-postprocessor/mask.ts
Labels: ready to merge

#928 fix(kit): `Placeholder` is not compatible with `maskitoEventHandler` + `focus`/`blur` events
  projects/demo-integrations/src/tests/recipes/placeholder/us-phone.cy.ts
  projects/demo/src/pages/recipes/placeholder/examples/1-cvc-code/component.ts
  projects/demo/src/pages/recipes/placeholder/examples/2-phone/component.ts
  projects/demo/src/pages/recipes/placeholder/examples/2-phone/mask.ts
  projects/demo/src/pages/recipes/placeholder/examples/3-date/component.ts
  projects/demo/src/pages/recipes/placeholder/placeholder-doc.component.ts
  projects/kit/src/lib/processors/tests/with-placeholder.spec.ts
  projects/kit/src/lib/processors/with-placeholder.ts
Labels: ready to merge

#935 chore: update `CHANGELOG.md`
  CHANGELOG.md
Labels: ready to merge

#937 fix(core): don't execute `setSelectionRange` if element is not focused
  projects/core/src/lib/mask.ts
  projects/core/src/lib/utils/dom/update-element.ts
  projects/kit/src/lib/plugins/caret-guard.ts
  projects/kit/src/lib/utils/get-focused.ts
  projects/kit/src/lib/utils/index.ts
Labels: ready to merge

#955 fix(kit): `Number` rejects the first time input of full width digits
  projects/kit/src/lib/masks/number/number-mask.ts
  projects/kit/src/lib/masks/number/tests/number-mask.spec.ts
Labels: ready to merge

#963 chore(kit): fix `Circular dependency` warning
  projects/kit/src/lib/utils/extract-affixes.ts
Labels: ready to merge

#962 fix(react): `@maskito/react` library should not include `core-js` imports
  projects/react/.babelrc
  projects/react/project.json
Labels: ready to merge

#977 fix(core): `maskitoUpdateElement` should not dispatch `InputEvent` if value is not changed
  projects/core/src/lib/utils/dom/update-element.ts
  projects/demo-integrations/src/tests/component-testing/initial-calibration-plugin/dispatch-event.cy.ts
  projects/demo-integrations/src/tests/component-testing/utils.ts
  projects/kit/src/lib/masks/number/plugins/leading-zeroes-validation.plugin.ts
  projects/kit/src/lib/masks/number/plugins/not-empty-integer.plugin.ts
Labels: ready to merge
